
export enum UserRole {
    ADMIN = "ADMIN",
    CHANNEL_PARTNER = "CHANNEL_PARTNER",
    TRAINER = "TRAINER",
    STUDENT = "STUDENT",
    CEO = "CEO",
    TELECALLER = "TELECALLER"
}

export enum LeadStatus {
    NEW = "NEW",
    CONTACTED = "CONTACTED",
    INTERESTED = "INTERESTED",
    QUALIFIED = "QUALIFIED",
    NEGOTIATING = "NEGOTIATING",
    NOT_INTERESTED = "NOT_INTERESTED",
    CALL_BACK_LATER = "CALL_BACK_LATER",
    DEMO_SCHEDULED = "DEMO_SCHEDULED",
    DEMO_ATTENDED = "DEMO_ATTENDED",
    READY_FOR_ADMISSION = "READY_FOR_ADMISSION",
    CONVERTED = "CONVERTED",
    LOST = "LOST"
}

export enum LeadSource {
    WEBSITE = "WEBSITE",
    PHONE = "PHONE",
    WALK_IN = "WALK_IN",
    REFERRAL = "REFERRAL",
    SOCIAL_MEDIA = "SOCIAL_MEDIA",
    ADVERTISEMENT = "ADVERTISEMENT",
    OTHER = "OTHER"
}

export enum AdmissionStatus {
    NEW = "NEW",
    CONTACTED = "CONTACTED",
    CONVERTED = "CONVERTED",
    CLOSED = "CLOSED"
}

export enum AttendanceStatus {
    PRESENT = "PRESENT",
    ABSENT = "ABSENT",
    LATE = "LATE",
    EXCUSED = "EXCUSED"
}

export enum PlacementStatus {
    NOT_ELIGIBLE = "NOT_ELIGIBLE",
    ELIGIBLE = "ELIGIBLE",
    APPLIED = "APPLIED",
    SHORTLISTED = "SHORTLISTED",
    INTERVIEWED = "INTERVIEWED",
    OFFERED = "OFFERED",
    PLACED = "PLACED",
    REJECTED = "REJECTED"
}

export enum IncentiveType {
    ADMISSION = "ADMISSION",
    PLACEMENT = "PLACEMENT",
    PERFORMANCE = "PERFORMANCE",
    BONUS = "BONUS"
}
