/**
 * Utility functions for generating and downloading reports.
 */

export const downloadSyllabusReport = (courseName: string, courseCode: string, syllabus: string) => {
    const reportTitle = `SYLLABUS REPORT: ${courseName.toUpperCase()} (${courseCode})`;
    const separator = "=".repeat(reportTitle.length);
    const date = new Date().toLocaleDateString();

    const reportContent = `
${separator}
${reportTitle}
${separator}
Date Generated: ${date}

COURSE OVERVIEW
---------------
Name: ${courseName}
Code: ${courseCode}

SYLLABUS CONTENT
----------------
${syllabus}

${separator}
Generated by Fortune Campus Management System
${separator}
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Syllabus_${courseName.replace(/\s+/g, '_')}_${courseCode}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
